version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Elixir Version
        VARIANT: "1.12.3"
        PHOENIX_VERSION: "1.6.0"
        NODE_VERSION: "12"

    init: true

    volumes:
      - ..:/workspace:cached
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  postgres-data: